<a href="https://colab.research.google.com/github/ayalavilla079/UTEC-Fundamentos-de-Programacion/blob/main/MODULO-II/%5B7%5D_Python_UTEC_161224.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# Llamar a la librería
import numpy as np

In [ ]:
# Crear un arreglo en numpy
arr_1 = np.array([2,4,6])

In [ ]:
# Visualizar el arreglo
print(f"El arreglo en numpy es \n{arr_1}")

El arreglo en numpy es 
[2 4 6]


In [ ]:
# Crear una lista
lista_1 = [2,4,6]
print(f"La lista es \n{lista_1}")

La lista es 
[2, 4, 6]


In [ ]:
print(f"El objeto arr_1 es del tipo \n{type(arr_1)}")
print(f"\nEl objeto lista_1 es del tipo \n{type(lista_1)}")

El objeto arr_1 es del tipo 
<class 'numpy.ndarray'>

El objeto lista_1 es del tipo 
<class 'list'>


In [ ]:
# Operaciones listas
print(f"El valor mínimo de la lista \n{lista_1} es {min(lista_1)}")
print(f"\nEl valor máximo de la lista \n{lista_1} es {max(lista_1)}")
print(f"\nLa suma total de la lista \n{lista_1} es {sum(lista_1)}")

El valor mínimo de la lista 
[2, 4, 6] es 2

El valor máximo de la lista 
[2, 4, 6] es 6

La suma total de la lista 
[2, 4, 6] es 12


In [ ]:
# El símbolo "+" permite concatenar listas
lista_1 + [5]

[2, 4, 6, 5]

In [ ]:
print(f"El arreglo en numpy es \n{arr_1}")
print(f"Suma del arreglo en numpy con 5 es \n{arr_1 + 5}")

El arreglo en numpy es 
[2 4 6]
Suma del arreglo en numpy con 5 es 
[ 7  9 11]


In [ ]:
# Crear arreglos de numpy

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(f"El arreglo a1 es \n{a1}")
print(f"\nEl arreglo a2 es \n{a2}")

El arreglo a1 es 
[1 2 3]

El arreglo a2 es 
[4 5 6]


In [ ]:
print(f"El arreglo a1 es del tipo \n{type(a1)}")
print(f"\nEl arreglo a2 es del tipo \n{type(a2)}")

El arreglo a1 es del tipo 
<class 'numpy.ndarray'>

El arreglo a2 es del tipo 
<class 'numpy.ndarray'>


In [ ]:
# Operaciones matemáticas con los arreglos de numpy
arr_sum = a1 + a2
arr_prod = a1 * a2
print(f"La suma de los arreglos es \n{arr_sum}")
print(f"\nLa multiplicación de los arreglos es \n{arr_prod}")

La suma de los arreglos es 
[5 7 9]

La multiplicación de los arreglos es 
[ 4 10 18]


In [ ]:
# Matrices de 2D
mat_4 = np.array([[1,2,3],[4,5,6]])
print(f"La matriz de 2D es \n{mat_4}")

La matriz de 2D es 
[[1 2 3]
 [4 5 6]]


In [ ]:
# Crear una lista de listas
ll_1 = [[10,20,30],[10,10,10]]
print(f"La lista de listas es \n{ll_1}")
print(f"\nEl objeto ll_1 es del tipo \n{type(ll_1)}")

La lista de listas es 
[[10, 20, 30], [10, 10, 10]]

El objeto ll_1 es del tipo 
<class 'list'>


In [ ]:
# Crear una matriz en numpy a partir de una lista

mat_6 = np.array(ll_1)
print(f"La matriz de 2D es \n{mat_6}")
print(f"\nEl objeto mat_6 es del tipo \n{type(mat_6)}")

La matriz de 2D es 
[[10 20 30]
 [10 10 10]]

El objeto mat_6 es del tipo 
<class 'numpy.ndarray'>


In [ ]:
# Creamos una matriz 1D a parit de arange
mat_7 = np.arange(15)
print(f"La matriz 1D de numpy es \n{mat_7}")
print(f"\nEl objeto mat_7 es del tipo \n{type(mat_7)}")

La matriz 1D de numpy es 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

El objeto mat_7 es del tipo 
<class 'numpy.ndarray'>


In [ ]:
# Crear una matriz 2D en numpy a partir de una matriz 1D
mat_8 = mat_7.reshape(3,5) #3 filas, 5 columnas
print(f"La matriz 2D de numpy es \n{mat_8}")
print(f"\nEl objeto mat_8 es del tipo \n{type(mat_8)}")

La matriz 2D de numpy es 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

El objeto mat_8 es del tipo 
<class 'numpy.ndarray'>


In [ ]:
print(f"El número de dimensiones del objeto mat_8 es {mat_8.ndim}")
print(f"\nEl tamaño de las dimensiones del objeto mat_8 es {mat_8.shape}")
print(f"\nEl número de elementos del objeto mat_8 es {mat_8.size}")

El número de dimensiones del objeto mat_8 es 2

El tamaño de las dimensiones del objeto mat_8 es (3, 5)

El número de elementos del objeto mat_8 es 15


In [ ]:
# Crear una matriz de ceros con determinadas dimensiones
mat_9 = np.zeros((4,3))

In [ ]:
# Las características de la matriz
print(f"La matriz mat_9 es \n{mat_9}")
print(f"\nEl objeto mat_9 es del tipo \n{type(mat_9)}")
print(f"\nEl número de dimensiones de la matriz mat_9 es {mat_9.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_9 es {mat_9.shape}")
print(f"\nEl número de elementos de la matriz mat_9 es {mat_9.size}")

La matriz mat_9 es 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

El objeto mat_9 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_9 es 2

El tamaño de las dimensiones de la matriz mat_9 es (4, 3)

El número de elementos de la matriz mat_9 es 12


In [ ]:
# Crear una matriz de valores espaciados en un intervalo
mat_10 = np.linspace(50,60,20)
# Las características de la matriz
print(f"La matriz mat_10 es \n{mat_10}")
print(f"\nEl objeto mat_10 es del tipo \n{type(mat_10)}")
print(f"\nEl número de dimensiones de la matriz mat_10 es {mat_10.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_10 es {mat_10.shape}")
print(f"\nEl número de elementos de la matriz mat_10 es {mat_10.size}")

La matriz mat_10 es 
[50.         50.52631579 51.05263158 51.57894737 52.10526316 52.63157895
 53.15789474 53.68421053 54.21052632 54.73684211 55.26315789 55.78947368
 56.31578947 56.84210526 57.36842105 57.89473684 58.42105263 58.94736842
 59.47368421 60.        ]

El objeto mat_10 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_10 es 1

El tamaño de las dimensiones de la matriz mat_10 es (20,)

El número de elementos de la matriz mat_10 es 20


In [ ]:
l_0 = [30,32,40,50,65]
print(f"El objeto l_0 es {l_0}")
print(f"El objeto l_0 es del tipo {type(l_0)}")

El objeto l_0 es [30, 32, 40, 50, 65]
El objeto l_0 es del tipo <class 'list'>


In [ ]:
mat_11 = np.array(l_0) # Convertir una lista en un arreglo numpy
print(f"El objeto mat_11 es {mat_11}")
print(f"El objeto mat_11 es del tipo {type(mat_11)}")

El objeto mat_11 es [30 32 40 50 65]
El objeto mat_11 es del tipo <class 'numpy.ndarray'>


In [ ]:
# Las características de la matriz
print(f"La matriz mat_11 es \n{mat_11}")
print(f"\nEl objeto mat_11 es del tipo \n{type(mat_11)}")
print(f"\nEl número de dimensiones de la matriz mat_11 es {mat_11.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_11 es {mat_11.shape}")
print(f"\nEl número de elementos de la matriz mat_11 es {mat_11.size}")

La matriz mat_11 es 
[30 32 40 50 65]

El objeto mat_11 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_11 es 1

El tamaño de las dimensiones de la matriz mat_11 es (5,)

El número de elementos de la matriz mat_11 es 5


In [ ]:
mat_12 = np.arange(24).reshape(2,4,3)
# Las características de la matriz
print(f"La matriz mat_12 es \n{mat_12}")
print(f"\nEl objeto mat_12 es del tipo \n{type(mat_12)}")
print(f"\nEl número de dimensiones de la matriz mat_12 es {mat_12.ndim}")
print(f"\nEl tamaño de las dimensiones de la matriz mat_12 es {mat_12.shape}")
print(f"\nEl número de elementos de la matriz mat_12 es {mat_12.size}")

La matriz mat_12 es 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

El objeto mat_12 es del tipo 
<class 'numpy.ndarray'>

El número de dimensiones de la matriz mat_12 es 3

El tamaño de las dimensiones de la matriz mat_12 es (2, 4, 3)

El número de elementos de la matriz mat_12 es 24
